### ISSUE TITLE
Issue when copying resources

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm#188] opened 2022-11-14 10:23 UTC
**What happened**:

The OCM CLI fails when transferring certain components with the `--copy resources` flag set. This seems to be occur when transferring larger images (>500mb). I have observed this behavior using both the CLI and the library, an example to reproduce using the CLI is below. 

**What you expected to happen**:

I expect all resources to be transferred.

**How to reproduce it (as minimally and precisely as possible)**:

The issue can be reproduced via the following commands:

```bash
git clone git@github.com:open-component-model/ocm-sock-shop.git

cd ocm-sock-shop

export GITHUB_USER={YOUR_GITHUB_USERNAME}

make all PROVIDER=$GITHUB_USER
```

The resource `db-image` (which refers to `docker.io/library/mongo:6.0.2`) will cause the transfer process to hang.

**Anything else we need to know**:

**Environment**:

```bash
> ocm version
version.Info{Major:"0", Minor:"1", Patch:"0", PreRelease:"", Meta:"e489d4af9897e144fe3fc11655fa94d1d00bb149", GitVersion:"0.1.0+e489d4af9897e144fe3fc11655fa94d1d00bb149", GitCommit:"e489d4af9897e144fe3fc11655fa94d1d00bb149", GitTreeState:"dirty", BuildDate:"2022-10-18T20:12:42+01:00", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by phoban01** [comment] 2022-11-14 11:31
Further context, the command eventually times out with the following error:

```
 unable to add blob: exploding OCI artefact resource blob ([library/mongo:6.0.2] namespace phoban01/orders/library/mongo: open blob): failed to transfer artifact: transferring indexed artefact sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7: transferring layer blob sha256:a48a3e4ae2de839d8e99bde16eb91d113fb2cf889bba472d0c4274851b5fb402: unable to copy blob content: write /tmp/VFS-2338277660/blobs/sha256.a48a3e4ae2de839d8e99bde16eb91d113fb2cf889bba472d0c4274851b5fb402: no space left on device
 ```

**Comment by mandelsoft** [comment] 2022-11-14 12:10
This is basically not the error I got, when trying to access this docker image.
My error could be solved by copying the image to gcr  ([eu.gcr.io/gardener-project/test/jensh007/mongo:6.0.4](http://eu.gcr.io/gardener-project/test/jensh007/mongo:6.0.4)).

The problem you described is caused by a volume which is too small in your controller.

When transferring images by value, the content is assembled in temporary files. Tose structures use the `/tmp` folder,
so, its volume must have an appropriate size

**Comment by mandelsoft** [comment] 2022-11-14 12:13
Nevertheless we urgently have to replace the used OCI library.

**Comment by mandelsoft** [comment] 2022-11-14 16:02
I found the problem:

The original mongo image is a multi arch image with several architectures inclusing windows variants,

The variants have partly large layers, which sum up to serveral GB.

If the index is transported by value, the complete content is packaged into an archive, which blows up the temp space.

Mitigation for th demo is to just use an image for the platforms required.

```
DEBU[0004] transfer OCI manifest                         digest="\"sha256:53c4915c2c13524007a84b472f8c0b0a3c4f889afcb014306b628b2e82d0b658\""
DEBU[0004] getting blob                                  digest="\"sha256:b70536aeb2507ba0ea53767d15d836e140ccf3df74f2678f0cb5dd5c5e1d952c\""
DEBU[0004] getting blob done                             digest="\"sha256:b70536aeb2507ba0ea53767d15d836e140ccf3df74f2678f0cb5dd5c5e1d952c\"" error=null size=7663
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83\""
DEBU[0004] getting blob done                             digest="\"sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83\"" error=null size=28577834
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:8a00eb9f68a0dcf2f4b6f3881376f35b2908e0ec03e0ba7b41dce5138a57017e\""
DEBU[0004] getting blob done                             digest="\"sha256:8a00eb9f68a0dcf2f4b6f3881376f35b2908e0ec03e0ba7b41dce5138a57017e\"" error=null size=1837
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:f683956749c518e0ea925e30c0c5115c4ce12e827cd34bcf72ce2e9d750a2bb6\""
DEBU[0004] getting blob done                             digest="\"sha256:f683956749c518e0ea925e30c0c5115c4ce12e827cd34bcf72ce2e9d750a2bb6\"" error=null size=3059607
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:b33b2f05ea206b8ad00c6db544ddc80db3b9f6f9ea070867894eb83acdd9656c\""
DEBU[0004] getting blob done                             digest="\"sha256:b33b2f05ea206b8ad00c6db544ddc80db3b9f6f9ea070867894eb83acdd9656c\"" error=null size=6509130
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:3a342bea915a9cfedf83084c321b2c1aae8bbfdc8aa1f0845669c4d325bff96d\""
DEBU[0004] getting blob done                             digest="\"sha256:3a342bea915a9cfedf83084c321b2c1aae8bbfdc8aa1f0845669c4d325bff96d\"" error=null size=149
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:fa956ab1c2f09b41dec38b203cd914272b87e515a3658915e57f3a686382c261\""
DEBU[0004] getting blob done                             digest="\"sha256:fa956ab1c2f09b41dec38b203cd914272b87e515a3658915e57f3a686382c261\"" error=null size=1447
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:138a8542a62498c9e71e1778b9b0bfbf522b4e549b83a9b4f64f7c1b671ae7df\""
DEBU[0004] getting blob done                             digest="\"sha256:138a8542a62498c9e71e1778b9b0bfbf522b4e549b83a9b4f64f7c1b671ae7df\"" error=null size=259
DEBU[0004] layer                                        
DEBU[0004] getting blob                                  digest="\"sha256:acab179a7f073886768651b76367c9845a10c2a53048b6c95f1b1424e86dea92\""
DEBU[0004] getting blob done                             digest="\"sha256:acab179a7f073886768651b76367c9845a10c2a53048b6c95f1b1424e86dea92\"" error=null size=193574943
DEBU[0005] layer                                        
DEBU[0005] getting blob                                  digest="\"sha256:f88335710e8418ba561f1d9505ee45125592f4f5d9ab248393041a53e3051f7a\""
DEBU[0005] getting blob done                             digest="\"sha256:f88335710e8418ba561f1d9505ee45125592f4f5d9ab248393041a53e3051f7a\"" error=null size=5069
DEBU[0005] transfer OCI manifest done                    error=null
DEBU[0005] indexed manifest                             
DEBU[0005] get artefact                                  ref="docker.io/library/mongo@sha256:b567c55036f586bc6cee739009fb81c144adf3806898a3d8910ff5d557d45a45"
DEBU[0007] done                                          digest="\"sha256:b567c55036f586bc6cee739009fb81c144adf3806898a3d8910ff5d557d45a45\"" error=null mimetype=application/vnd.docker.distribution.manifest.v2+json size=2202
DEBU[0007] transfer OCI manifest                         digest="\"sha256:b567c55036f586bc6cee739009fb81c144adf3806898a3d8910ff5d557d45a45\""
DEBU[0007] getting blob                                  digest="\"sha256:1a5c8f74cf956d352341b9ec6530cc0341ffd4cd58cebde205ce254d2203b715\""
DEBU[0007] getting blob done                             digest="\"sha256:1a5c8f74cf956d352341b9ec6530cc0341ffd4cd58cebde205ce254d2203b715\"" error=null size=7681
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:4e7e0215f4adc2c48ad9cb3b3781e21d474b477587f85682c2e2975ae91dce9d\""
DEBU[0007] getting blob done                             digest="\"sha256:4e7e0215f4adc2c48ad9cb3b3781e21d474b477587f85682c2e2975ae91dce9d\"" error=null size=27195998
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:bffac05d305dafc7bd6d968c4d611342ceb95a87494c361ab37718b188f02763\""
DEBU[0007] getting blob done                             digest="\"sha256:bffac05d305dafc7bd6d968c4d611342ceb95a87494c361ab37718b188f02763\"" error=null size=1840
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:6d44feb31079d0e2421a83a8dd5563d203ec1ff537396d3ed65dd35cdfed206f\""
DEBU[0007] getting blob done                             digest="\"sha256:6d44feb31079d0e2421a83a8dd5563d203ec1ff537396d3ed65dd35cdfed206f\"" error=null size=2907461
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:bd79df0bf56efa1ec22177052bd5d6e4feef423ad95176bd0f86a478f3f99d30\""
DEBU[0007] getting blob done                             digest="\"sha256:bd79df0bf56efa1ec22177052bd5d6e4feef423ad95176bd0f86a478f3f99d30\"" error=null size=6425791
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:393c4defd29fb265c4d4794d5f008fbde7c8d9c4f91a7105e9cf2866a28df77a\""
DEBU[0007] getting blob done                             digest="\"sha256:393c4defd29fb265c4d4794d5f008fbde7c8d9c4f91a7105e9cf2866a28df77a\"" error=null size=149
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:be2da71c1f524304c6fddcfd682ea28128baf5f08cadfbf5b9c0ad090af3831d\""
DEBU[0007] getting blob done                             digest="\"sha256:be2da71c1f524304c6fddcfd682ea28128baf5f08cadfbf5b9c0ad090af3831d\"" error=null size=1441
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:0b4c4322236bd8250387800e057c330d487ebf386f2d007d7ccb8bc9aabc13e1\""
DEBU[0007] getting blob done                             digest="\"sha256:0b4c4322236bd8250387800e057c330d487ebf386f2d007d7ccb8bc9aabc13e1\"" error=null size=259
DEBU[0007] layer                                        
DEBU[0007] getting blob                                  digest="\"sha256:2f4baaecdab319402fa206222759f080d7bd645002f9ad3a1ddb6b4e32204110\""
DEBU[0007] getting blob done                             digest="\"sha256:2f4baaecdab319402fa206222759f080d7bd645002f9ad3a1ddb6b4e32204110\"" error=null size=188585988
DEBU[0008] layer                                        
DEBU[0008] getting blob                                  digest="\"sha256:c2076034e8003a37c5a97f6f6d582de741fd3a0b4a1f4dd671b148023f85c00e\""
DEBU[0008] getting blob done                             digest="\"sha256:c2076034e8003a37c5a97f6f6d582de741fd3a0b4a1f4dd671b148023f85c00e\"" error=null size=5072
DEBU[0008] transfer OCI manifest done                    error=null
DEBU[0008] indexed manifest                             
DEBU[0008] get artefact                                  ref="docker.io/library/mongo@sha256:6c76367747757ba6897dca28ff0d3359c46216a0e5c9932efc5166bcf3aa8920"
DEBU[0009] done                                          digest="\"sha256:6c76367747757ba6897dca28ff0d3359c46216a0e5c9932efc5166bcf3aa8920\"" error=null mimetype=application/vnd.docker.distribution.manifest.v2+json size=2414
DEBU[0009] transfer OCI manifest                         digest="\"sha256:6c76367747757ba6897dca28ff0d3359c46216a0e5c9932efc5166bcf3aa8920\""
DEBU[0009] getting blob                                  digest="\"sha256:67f484e92419400ca1fe01c9b8d16981964fe62e9bffe5dd1736dd4b6898c8b9\""
DEBU[0009] getting blob done                             digest="\"sha256:67f484e92419400ca1fe01c9b8d16981964fe62e9bffe5dd1736dd4b6898c8b9\"" error=null size=5340
DEBU[0009] layer                                        
DEBU[0009] getting blob                                  digest="\"sha256:a4aee932fccc1ec8135f290aca03a7c93dcc2536fc84723813ef9b95f6fd13ea\""
DEBU[0009] getting blob done                             digest="\"sha256:a4aee932fccc1ec8135f290aca03a7c93dcc2536fc84723813ef9b95f6fd13ea\"" error=null size=1473997635
DEBU[0018] layer                                        
DEBU[0018] getting blob                                  digest="\"sha256:e276673195ed11807395b0da51ac20ef31c925ce955c29ad1bab54f14617c25b\""
DEBU[0018] getting blob done                             digest="\"sha256:e276673195ed11807395b0da51ac20ef31c925ce955c29ad1bab54f14617c25b\"" error=null size=1007770983
DEBU[0023] layer                                        
DEBU[0023] getting blob                                  digest="\"sha256:edcc0cd10e58716558145d847bcea390e3840d172df19b8d0f08a57dd985262d\""
DEBU[0023] getting blob done                             digest="\"sha256:edcc0cd10e58716558145d847bcea390e3840d172df19b8d0f08a57dd985262d\"" error=null size=1381
DEBU[0023] layer                                        
DEBU[0023] getting blob                                  digest="\"sha256:2181e1adb6da783ef737efe46eb9aa253d785a46843f0b8a12301b7337d15c04\""
DEBU[0023] getting blob done                             digest="\"sha256:2181e1adb6da783ef737efe46eb9aa253d785a46843f0b8a12301b7337d15c04\"" error=null size=1397
DEBU[0023] layer                                        
DEBU[0023] getting blob                                  digest="\"sha256:456decbcd5c74457855fbaf2b027f6819683fcb87441e6643f44542f9a5cdb56\""
DEBU[0023] getting blob done                             digest="\"sha256:456decbcd5c74457855fbaf2b027f6819683fcb87441e6643f44542f9a5cdb56\"" error=null size=1430
DEBU[0023] layer                                        
DEBU[0023] getting blob                                  digest="\"sha256:9d748c55105ec09d7403ba625dfe485918bbfec20a980bc1af45f3180a8dc909\""
DEBU[0023] getting blob done                             digest="\"sha256:9d748c55105ec09d7403ba625dfe485918bbfec20a980bc1af45f3180a8dc909\"" error=null size=1423
DEBU[0023] layer                                        
DEBU[0023] getting blob                                  digest="\"sha256:a889f81d86650d9c1bae3ce2ed0287812fc0680d580bf549d0f4a43715d6c133\""
DEBU[0023] getting blob done                             digest="\"sha256:a889f81d86650d9c1bae3ce2ed0287812fc0680d580bf549d0f4a43715d6c133\"" error=null size=512685887
DEBU[0026] layer                                        
DEBU[0026] getting blob                                  digest="\"sha256:964d726a83c6a1293392e10654a23d7ef4998c6643bc87364213446e2904e5cd\""
DEBU[0026] getting blob done                             digest="\"sha256:964d726a83c6a1293392e10654a23d7ef4998c6643bc87364213446e2904e5cd\"" error=null size=1395
DEBU[0026] layer                                        
DEBU[0026] getting blob                                  digest="\"sha256:244ae10be776babe53eef1e437574e8624aa0d9b7b3ea34386721d61af82ac7a\""
DEBU[0026] getting blob done                             digest="\"sha256:244ae10be776babe53eef1e437574e8624aa0d9b7b3ea34386721d61af82ac7a\"" error=null size=1414
DEBU[0026] layer                                        
DEBU[0026] getting blob                                  digest="\"sha256:f7a8eed089b637c7348d6490113e5ed7391de0ecbda52eb9b92b869aa5a198c8\""
DEBU[0026] getting blob done                             digest="\"sha256:f7a8eed089b637c7348d6490113e5ed7391de0ecbda52eb9b92b869aa5a198c8\"" error=null size=1426
DEBU[0026] transfer OCI manifest done                    error=null
DEBU[0026] indexed manifest                             
DEBU[0026] get artefact                                  ref="docker.io/library/mongo@sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7"
DEBU[0027] done                                          digest="\"sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7\"" error=null mimetype=application/vnd.docker.distribution.manifest.v2+json size=2413
DEBU[0027] transfer OCI manifest                         digest="\"sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7\""
DEBU[0027] getting blob                                  digest="\"sha256:2eecef695ec74bd59d29fd578d4be6f56a5fd070d32351df46f030ab2a53a807\""
DEBU[0027] getting blob done                             digest="\"sha256:2eecef695ec74bd59d29fd578d4be6f56a5fd070d32351df46f030ab2a53a807\"" error=null size=5341
DEBU[0027] layer                                        
DEBU[0027] getting blob                                  digest="\"sha256:a48a3e4ae2de839d8e99bde16eb91d113fb2cf889bba472d0c4274851b5fb402\""
DEBU[0027] getting blob done                             digest="\"sha256:a48a3e4ae2de839d8e99bde16eb91d113fb2cf889bba472d0c4274851b5fb402\"" error=null size=1924269350
DEBU[0039] layer                                        
DEBU[0039] getting blob                                  digest="\"sha256:c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091\""
DEBU[0039] getting blob done                             digest="\"sha256:c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091\"" error=null size=854317461
DEBU[0042] transfer OCI manifest done                    error="\"transferring layer blob sha256:c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: unable to copy blob content: write /tmp/VFS-611208454/blobs/sha256.c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: no space left on device\""
DEBU[0042] transfer OCI index done                       error="\"transferring indexed artefact sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7: transferring layer blob sha256:c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: unable to copy blob content: write /tmp/VFS-611208454/blobs/sha256.c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: no space left on device\""
DEBU[0043] synthesize artefact blob done                 error="\"failed to transfer artifact: transferring indexed artefact sha256:78b2e7438587e7a5653fb03bb8a5c25d280e8597f02a25939de96e6921b697b7: transferring layer blob sha256:c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: unable to copy blob content: write /tmp/VFS-611208454/blobs/sha256.c26cc6e4f9eb1ae415a5ead6f884cac597bbd57efa6cd042c878d5b54c9d2091: no space left on device\"" ref="library/mongo:6.0.2"
DEBU[0043] synthesize artefact blob                      ref="library/mongo:6.0.2"

**Closed** 2022-11-16 13:11 UTC
Labels: kind/bug
