### ISSUE TITLE
Simplify and Refactor the OCM CLI Project Structure

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm#430] opened 2023-07-13 13:33 UTC
# User Story

## Description
As a developer using the OCM CLI, I want the project structure to be simplified and organized to improve usability and maintainability. Currently, the structure is complex, making it difficult to find the entry point for each command. Additionally, there are unnecessary subprojects and packages in the `cmd/` directory, such as 'helminstaller' and 'toi,' which should be removed. Considering the complexity and potential future enhancements, it may be beneficial to explore the possibility of splitting OCM into `ocm-cli` and `ocm-core` to ensure a more modular and manageable architecture.

**Epic link**:
- #390 

## Potential Tasks
1. Refactor the project structure to simplify the OCM CLI codebase:
   - Review the current directory structure and eliminate unnecessary subprojects.
   - Identify common functionalities that can be abstracted into reusable modules.
   - Aim for a single file per command to improve discoverability and maintainability.

2. Remove unnecessary subprojects and packages:
   - Assess the 'helminstaller' and 'toi' subprojects to determine if they are still required.
   - If deemed unnecessary, remove the corresponding packages and dependencies from the project.

3. Explore the possibility of splitting OCM into `ocm-cli` and `ocm-core`:
   - Evaluate the benefits and drawbacks of modularizing the CLI functionality into a separate `ocm-cli` project and a shared `ocm-core` project.
   - Define the boundaries and responsibilities of each module to ensure a clear and maintainable architecture.
   - Plan the migration process and consider the impact on existing users and contributors.

## Definition of Done
- [ ] The project structure is refactored and simplified.
- [ ] Unnecessary subprojects and packages (`helminstaller` and `toi`) are removed.
- [ ] Each command has a single file as the entry point, improving discoverability.
- [ ] The feasibility and benefits of splitting OCM into `ocm-cli` and `ocm-core` are evaluated and documented.
- [ ] If decided to split, the boundaries and responsibilities of each module are clearly defined.
- [ ] Migration plan and impact analysis for existing users and contributors are outlined.

**Related issues**:
- #292  
- (add related issues )

From brainstorming:
>CLI: Structure of the CLI project too complex
CLI: cmds/ directory should not have packages or unnecessary subprojects such as helminstaller and toi
CLI: should aim for single file per command; currently very difficult to find the entrypoint.
CLI: Potentially Split OCM into ocm-cli & ocm-core

**Comment by morri-son** [comment] 2024-02-15 13:09
close as duplicate of #655

**Closed by morri-son** 2024-02-15 13:09 UTC
Labels: kind/enhancement
